#!/usr/bin/env node

/**
 * Rebuilds the master KNOWLEDGE_INDEX.md from all processed sources.
 * Groups by type and topic, creates cross-references.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SOURCES_FILE = join(ROOT, 'sources.json');
const INDEX_FILE = join(ROOT, 'KNOWLEDGE_INDEX.md');
const KNOWLEDGE_DIR = join(ROOT, 'knowledge');

function main() {
  const sources = JSON.parse(readFileSync(SOURCES_FILE, 'utf-8'));
  const allSources = sources.sources;

  // Group by type
  const byType = {};
  for (const s of allSources) {
    if (!byType[s.type]) byType[s.type] = [];
    byType[s.type].push(s);
  }

  // Collect all topics
  const topicMap = {};
  for (const s of allSources) {
    for (const t of s.topics || []) {
      if (!topicMap[t]) topicMap[t] = [];
      topicMap[t].push(s);
    }
  }

  // Stats
  const stats = {
    total: allSources.length,
    processed: allSources.filter(s => s.status === 'processed').length,
    pending: allSources.filter(s => s.status === 'pending').length,
    types: Object.keys(byType).length,
    topics: Object.keys(topicMap).length,
  };

  const typeLabels = {
    'github-repo': { emoji: '📦', label: 'GitHub Repositories', dir: 'github-repos' },
    'article': { emoji: '📄', label: 'Articles & Documentation', dir: 'articles' },
    'youtube': { emoji: '🎥', label: 'YouTube Videos', dir: 'youtube' },
    'startup': { emoji: '🚀', label: 'Startups & Products', dir: 'startups' },
    'tool': { emoji: '🔧', label: 'Tools & Utilities', dir: 'articles' },
    'paper': { emoji: '📚', label: 'Research Papers', dir: 'articles' },
  };

  // Build index
  let md = `# DP Patel AI Knowledge Index

> Auto-generated master index of all knowledge base sources. Last updated: ${new Date().toISOString().split('T')[0]}

## Stats

| Metric | Count |
|--------|-------|
| Total Sources | ${stats.total} |
| Processed | ${stats.processed} |
| Pending | ${stats.pending} |
| Source Types | ${stats.types} |
| Topics | ${stats.topics} |

---

## By Source Type

`;

  for (const [type, items] of Object.entries(byType)) {
    const info = typeLabels[type] || { emoji: '📌', label: type, dir: 'articles' };
    md += `### ${info.emoji} ${info.label} (${items.length})\n\n`;
    md += `| Source | Topics | Status | Added |\n`;
    md += `|--------|--------|--------|-------|\n`;
    for (const s of items) {
      const docLink = `[${s.title || s.id}](knowledge/${info.dir}/${s.id}.md)`;
      md += `| ${docLink} | ${(s.topics || []).slice(0, 3).join(', ')} | ${s.status} | ${s.added} |\n`;
    }
    md += '\n';
  }

  md += `---\n\n## By Topic\n\n`;

  const sortedTopics = Object.entries(topicMap).sort((a, b) => b[1].length - a[1].length);
  for (const [topic, items] of sortedTopics) {
    md += `### ${topic} (${items.length} source${items.length > 1 ? 's' : ''})\n\n`;
    for (const s of items) {
      const info = typeLabels[s.type] || { emoji: '📌', dir: 'articles' };
      md += `- ${info.emoji} [${s.title || s.id}](knowledge/${info.dir}/${s.id}.md)\n`;
    }
    md += '\n';
  }

  md += `---\n\n## Recently Added\n\n`;

  const recent = [...allSources].sort((a, b) => b.added.localeCompare(a.added)).slice(0, 10);
  for (const s of recent) {
    const info = typeLabels[s.type] || { emoji: '📌', dir: 'articles' };
    md += `- **${s.added}** — ${info.emoji} [${s.title || s.id}](knowledge/${info.dir}/${s.id}.md)\n`;
  }

  md += `\n---\n\n## Quick Reference\n\n`;
  md += `### All Source URLs\n\n`;
  for (const s of allSources) {
    md += `- [${s.title || s.id}](${s.url})\n`;
  }

  md += `\n---\n\n*Generated by AIKnowledgebase build-index.js — ${new Date().toISOString()}*\n`;

  writeFileSync(INDEX_FILE, md);
  console.log(`Knowledge index built: ${INDEX_FILE}`);
  console.log(`  ${stats.total} sources, ${stats.topics} topics`);
}

main();
